spring:
  jpa:
    hibernate:
      dialect: "org.hibernate.dialect.MySQL5InnoDBDialect storage-engine:innodb"
    properties: local
  profiles:
    active: local
    include: "ouath,real-db"
  session:
    store-type: jdbc