spring:
  profiles:
    include: ouath,real-db
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
          storage-engine:innodb

  session:
    store-type: jdbc